site_name: Killifish
site_url: https://wjking0.github.io/killifish/
site_description: Killifish documentation with Markdown.
site_author: wking0@gmail.com

#repo_url: https://github.com/wjking0/killifish
edit_uri: ""

nav:
- Home: killifish_howtos.md


theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: indigo

  features:
    - navigation.tabs
    - navigation.sections
# extra_css:
#     - css/extra.css

# markdown_extensions:
#     - toc:
#         permalink: 
#     - admonition
#     - def_list
#     - mdx_gh_links:
#         user: mkdocs
#         repo: mkdocs

# copyright: Copyright &copy; 2014 <a href="https://twitter.com/_tomchristie">Tom Christie</a>, Maintained by the <a href="/about/release-notes/#maintenance-team">MkDocs Team</a>.
# google_analytics: ['UA-27795084-5', 'mkdocs.org']

plugins:
    - search
